Items index
Creiwry/kitten_project pull request #12
Opened 2023-08-28 17:51 UTC by Loulergue-jm

### What does this PR do?
set specific css file for the view index on items

2023-08-28 19:14 UTC, Creiwry commented on app/views/items/_form.html.erb
> +  <%= file_field_tag :avatar %>
Please edit this so it is linked to the form variable. An example from the previous eventbrite app we made was something like this:
 <%= form.label :avatar, style: "display: block", class: "form-label" %>
 <%= form.file_field :avatar, class: "form-control" %>
When we use the |form| pipe variable, we want to ensure that all the form fields are tied to it. Here is a helper you want to use for this case: https://apidock.com/rails/v6.0.0/ActionView/Helpers/FormHelper/file_field

2023-08-28 19:15 UTC, Creiwry commented
Also, please link the trello ticket and user story in the pull request body.

2023-08-28 19:22 UTC, Creiwry requested changes

2023-08-28 19:22 UTC, Creiwry commented on app/views/items/_form.html.erb
> +<% end %>
Please edit this so it is linked to the form variable. An example from the previous eventbrite app we made was something like this:
<%= form.label :avatar, style: "display: block", class: "form-label" %>
<%= form.file_field :avatar, class: "form-control" %>
When we use the |form| pipe variable, we want to ensure that all the form fields are tied to it. Here is a helper you want to use for this case: https://apidock.com/rails/v6.0.0/ActionView/Helpers/FormHelper/file_field

2023-08-28 20:24 UTC, Loulergue-jm commented on app/views/items/_form.html.erb
> +<% end %>
I didn't make any change in _form.html.erb
I only worked in index for the time being

2023-08-28 20:36 UTC, Loulergue-jm commented
Trello: Faire la page d'index des produits

2023-08-28 21:05 UTC, Creiwry commented on app/views/items/_form.html.erb
> +<% end %>
In that case, you probably pasted the code there and forgot to delete it, as this code is shown to be added in your pull request. Please delete these lines from your code and commit and push again. This will update the pull request.

2023-08-28 21:07 UTC, Creiwry commented
Please have a look at the edited pull request. I have added two links, the first to the trello issue, the second to the trello user story. It was briefly mentioned briefly in the group chat that we should be doing this now, but as the whole team wasn't present, we'll explain it fully tomorrow morning.

2023-08-29 06:48 UTC, Loulergue-jm commented on app/views/items/_form.html.erb
> +<% end %>
don't know how to delete these lines from my commit, we'll see how to deal with that together when you are connected, thanks

2023-08-29 14:30 UTC, Creiwry submitted a review, later dismissed
Resolved merge conflicts and checked functionality in browser

2023-08-29 14:30 UTC, merged