Front signin sign up
Creiwry/kitten_project pull request #19
Opened 2023-08-29 11:58 UTC by kirouackp0

### Ticket Link
(Found on Trello in your ticket description)
https://trello.com/c/sNHXVUTS

### User Story
(Linked to on Trello in your ticket description)
https://trello.com/c/JMOoUKw2

### What does this PR do?
(Your answer here.)
provides tentative front end for user registration page (CSS still needs work and JS to be added)

### Where should the reviewer start?
(Your answer here.)
I don't recommend reviewing in detail as this was a test commit done in order to pull most recent gemfile update.

### How should this be manually tested?
N/A

### Any background context you want to provide?
N.A

### Screenshots (if appropriate)
N.A

### Are there any breaking changes?
Jesus I hope not

2023-08-29 14:13 UTC, Creiwry commented
If this is just a tentative version, no need to do a PR yet. As long as you haven't changed layout massively so the others need to know, it's ok to keep committing to your branch per feature and then update PR with new information once the code is more complete.

2023-08-30 12:26 UTC, kirouackp0 commented
New commit - ready to merge

2023-08-30 14:09 UTC, greg-Da requested changes
Est ce que tu peux faire un `git pull origin main` et gerer les conflits je peux pas le faire puisque tu es sur un fork

2023-08-30 14:09 UTC, greg-Da commented on Gemfile
> +gem "tailwindcss-rails", "~> 2.0"
On a supprimé tailwind de l app

2023-08-30 14:09 UTC, greg-Da commented on Procfile.dev
Il faut supprimer ce fichier

2023-08-30 16:03 UTC, kirouackp0 commented on Procfile.dev
Fait

2023-08-30 16:04 UTC, kirouackp0 commented on Gemfile
> +gem "tailwindcss-rails", "~> 2.0"
Supprimé

2023-08-31 20:48 UTC, merged